runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: index.html

- url: /firebase/DatabaseService.*
  script: /firebase/Firebase.php

- url: /twilio/Messages.*
  script: /twilio/Messages.php

- url: /twilio/Calls.*
  script: /twilio/Calls.php

- url: /twilio.html
  script: twilio.html

- url: /bootstrap-3.3.4-dist
  static_dir: bootstrap-3.3.4-dist

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$
